name = "DecisionTrees"
uuid = "24bdfa7e-30e5-4580-8c2f-6078a053d616"
authors = ["Jan Pikman"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.8"
